server:
  port: 9002

spring:
  application:
    name: gateway-cloud
  cloud:
    #从注册中心动态创建路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #id：实例唯一ID;uri：真实服务地址；predicates：断言匹配；
        - id: provider-route
          uri: lb://PROVIDER-PAYMENT-SERVICE
          predicates:
            - Path=/ribbon/**
eureka:
  instance:
    #服务名称
    hostname: gateway-cloud
  client:
    serviceUrl:
      #eureka注册中心地址
      defaultZone: http://localhost:7000/eureka/  #配置URL
    #是否将自己注册到EurekaServer
    register-with-eureka: true
    #是否从EurekaServer获取已有的注册服务
    fetch-registry: true

