server:
  port: 7001

eureka:
  instance:
    #服务名称
    hostname: eureka-server-slave
  client:
    serviceUrl:
      #eureka注册中心地址
      defaultZone: http://localhost:7000/eureka/  #配置URL
    #不注册自己
    register-with-eureka: false
    #服务发现，false表示自己不从Eureka服务中获取注册信息
    fetch-registry: false
